#ifndef __MUART_CONFIG_H__
#define __MUART_CONFIG_H__

#define MUART_RX_INTERRUPT_ENABLE     MUART_DISABLED
#define MUART_TX_INTERRUPT_ENABLE     MUART_DISABLED
#define MUART_UDR_INTERRUPT_ENABLE    MUART_DISABLED
#define MUART_RIECEVE_ENABLE          MUART_ENABLED
#define MUART_SEND_ENABLE             MUART_ENABLED
#define MUART_MODE_SELECT             MUART_ASYNCHRONOUS
#define MUART_PARITY_MODE             MUART_DISABLED
#define MUART_STOP_BIT_NO             MUART_1_STOP_BIT
#define MUART_CHAR_SIZE               MUART_8_BITS
#define MUART_CLOCK_POLARITY          MUART_SAMPLE_FALLING_EDGE
#define MUART_BAUD_RATE               MUART_BAUDRATE_9600

#endif